# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build lettrines
        run: mpost lettrines.mp
        working-directory: lettrines

      - name: Build English pdf
        run: lualatex -interaction=nonstopmode byrne-en-latex.tex && lualatex -interaction=nonstopmode byrne-en-latex.tex

      - name: Build Russian pdf
        run: lualatex -interaction=nonstopmode byrne-ru-latex.tex && lualatex -interaction=nonstopmode byrne-ru-latex.tex

      - uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: byrne*latex.pdf
